//initialize weather sequence
//to apply specific weather to specific map go to this file
#include "we4ther_eff3cts/weather/main_event.zc"

//next files are important, since its how all system works "under the hood"
//change something there only if you REALLY know what you are doing
//control weather inside sector
#include "we4ther_eff3cts/weather/sector_weather_handler.zc"
//spawner of a snow/rain/etc.
#include "we4ther_eff3cts/weather/percipitation_spawner.zc"
//actual thing which actually shows as snow/rain/etc
#include "we4ther_eff3cts/weather/actual_precipitation.zc"
//rain sound
#include "we4ther_eff3cts/weather/specific_effects/rain_sound.zc"
//thunder sound
#include "we4ther_eff3cts/weather/specific_effects/thunder_sound.zc"

//thing that read weather definition
#include "we4ther_eff3cts/lump_parser/c_like_parser.zc"
#include "we4ther_eff3cts/lump_parser/weather_definition.zc"
